version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mycoolsql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: MattM
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: unless-stopped
  FeaturedFilm:
    build:
      context: .
    image: featured:latest
    container_name: featured
    ports:
    - "3002:3002"
    links:
    - mysql:mysql
    depends_on:
    - mysql
